### ISSUE TITLE
Java Fork

### ISSUE THREAD

**Issue by Stomarver** [PixelAlphas/Devamped#1]
can I port this resource pack to **java**?

**Comment by PixelAlphas** [comment]
Uh, nope. not yet. though I'm planning to port into java soon after I finish items and bedrock related UIs. though as for now java porting isn't my priority yet.

**Comment by Ziziiiiiiiiii** [comment]
The new release has a tiny visual glitch
![Screenshot_20230712-002611](https://github.com/PixelAlphas/Devamped/assets/139255721/239544e3-21ec-4898-a4ce-b5e4e1f98499)

**Comment by Ziziiiiiiiiii** [comment]
The latest devamped update has a tiny bit of visual bug on
![Uploading Screenshot_20230712-002611.jpg…]()
![Uploading Screenshot_20230712-002611_1.jpg…]()
 the potion effects thingy

**Comment by Ziziiiiiiiiii** [comment]
The latest devamped update has a tiny bit of visual bug on the status effect
![Screenshot_20230712-002611_1](https://github.com/PixelAlphas/Devamped/assets/139255721/212ee2d7-b4ca-4a37-861b-81de1578aff7)

**Comment by PixelAlphas** [comment]
This one are vanilla issues with replacing GUI related texture, I'll add the temporary vanilla effect icons order to fix this.

**Comment by PixelAlphas** [comment]
Java edition port has been released and therefore that issue is resolved.
